name: 'Check Render Preview'
description: 'Check the statuses of Render Preview Environments'
inputs:
  GITHUB_PR_ID:
    description: 'Pull Request number'
    required: false
    default: ${{ github.event.number }}
  BRANCH_NAME:
    description: 'The branch deployed by your Render Blueprint'
    required: false
    default: master
  SERVICE_NAME:
    description: 'The name of the Render service for which to check deployment status'
    required: true
outputs:
  env_status:
    description: 'The Preview Environment Deployment status'
  env_url:
    description: 'The Preview Environment Deployment URL for the Render service from SERVICE_NAME'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  color: 'orange'
  icon: 'refresh-ccw'